### ISSUE TITLE
'Calibrate Chain Length' motor speed

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/Firmware#144]
Currently runs at 500mm per minute. Can this be faster? How often is this calibration needed, would users do it more often if it took less time?

**Comment by BarbourSmith** [comment]
Yes, it can absolutely be faster. I was having issues with my chains becoming tangled when it ran full speed, but I think we can probably go faster without problems.

**Comment by blurfl** [comment]
If I had a couple more pieces of 'stretchy string', I'd use them to pull the end of the chain toward the opposite bottom corner, or something. I'm doing that now with garden twine, but some tension would be good.

**Comment by BarbourSmith** [comment]
In theory calibrating the chain lengths is something we *should* only have to do once when we setup the machine. While debugging it comes up all the time tho, so it's worth thinking of better ways.

**Comment by blurfl** [comment]
I guess the gearing is tall enough that gravity won't unwind it if the sled hangs with the power off. Do you leave your sled hanging, or rest it on something between sessions?

**Comment by BarbourSmith** [comment]
I leave it hanging unless I'm working on something. There is also a worm gear in there that you can't back drive so the motors are locked when powered down so in theory you can finish cutting something, power everything down, walk away, and then power everything back up and it will all be ready to go. That seems to be true unless you pull the USB cord while the machine is running, then you need to redo calibrate chain lengths.

**Comment by blurfl** [comment]
Good to know, thanks.
