### ISSUE TITLE
make g0 move at the machines max speed

### ISSUE THREAD

**Issue by davidelang** [MaslowCNC/Firmware#189]
G0 is supposed to always move at the machines max speed, while G1 moves at the defined feed rate. Currently there is no difference between the two.

**Comment by BarbourSmith** [comment]
Good point. The way it works right now is that G1 moves the machine at a defined speed, while G0 always moves the machine at it's maximum speed which is 48ipm. 

The real spec for G0 is to run both motors at full speed until it gets where it should be. I found that this caused undesired behavior near the edges of the 4*8 area when one motor had much more distance to cover than the other causing the sled to leave the 4*8 space. That is why I removed the original G0 code and instead do a coordinated move at 48ipm.

**Comment by davidelang** [comment]
g0 is defined as being a coordinated move, and since that doesn't get you to the 
final position any slower than an uncoordinated move (you are still limited by 
the axis that takes the longest to get there), it doesn't harm anything.

I missed the code that detected the difference between g0 and g1
