### ISSUE TITLE
add direction option for Z axis motors

### ISSUE THREAD

**Issue by davidelang** [MaslowCNC/Firmware#204]
between different ways of attaching a screw to the router, different directions to mount the motor from, and use of belts, there are many possible reasons why the z-axis motor may need to run in the opposite direction.

If this was during the design stage, I'd suggest that the plugs be made so that reversing a plug would reverse the direction the motor spins, but we're far past that.

In any case, software is easier to change than hardware, so there should be a config option on the main board to run the motor in the opposite direction.

The same thing should go for any use of the spare axis (and ideally for the main two, but it's hard to imagine why they would need to change right now, but in the interest of future-proofing things, it would probably be good to go ahead and include them)

**Comment by walter** [comment]
Background discussion can be found [here](http://www.maslowcnc.com/forums/#!/general:my-z-struggles/after-running-the-test-shap).

**Comment by BarbourSmith** [comment]
Great news everyone!

This feature actually already exists, just put a negative number in for the thread pitch and it will reverse the direction of motion. 
![negitive values](https://cloud.githubusercontent.com/assets/9359447/25670802/b83f7fb0-2fe2-11e7-97f4-fdd6b6c81424.JPG)
