### ISSUE TITLE
Stutter in left motor

### ISSUE THREAD

**Issue by designfrontier** [MaslowCNC/Firmware#282]
https://www.youtube.com/watch?v=OjlU1UJpnog

The left motor seems to stutter when cutting and moving z-index on firmware v0.82 for me. The video shows it moving in and out. The video is of it cutting a 1 1/8" circle in 3/4 ply.

Cut settings are 25 ipm feed rate, 30ipm z feed rate, 0.15 in step down. Wasn't as pronounced in v0.80 for me but now it is very pronounced. Even vertical cuts are showing a heavy stutter.

I'll see if I can pull the correct lines out of the gcode file when I have some time. The right motor remains steady and stutter free.

**Comment by davidelang** [comment]
it seems to be problems with the PID tuning being overly aggressive, there are 
several threads on this, look at the forum topic "do I have a bad motor" (or 
something similar to that)

There is an experimental GC and firmware branch to allow tuning of these.

David Lang

**Comment by designfrontier** [comment]
@davidelang is it the triangular kinematics branch?

**Comment by davidelang** [comment]
no, that is for dealing with a sled with different chain mounting.
kk

**Comment by BarbourSmith** [comment]
You want the master version of both the firmware and Ground Control. Both need to be updated to 0.83 (the version on master of both right now) for the changes to work

**Comment by designfrontier** [comment]
thanks @BarbourSmith I just saw that in the forum. It will probably be tomorrow at the earliest, and the weekend at the latest, before I can test it out.

**Comment by designfrontier** [comment]
did some test cuts this morning... much much smoother. A little chatter on z moves from the right motor. Is there a place in groundcontrol to tweak the PID settings? I could not for the life of me find it

**Comment by BarbourSmith** [comment]
Yes! It's under Advanced Settings (open settings, then click the Maslow Settings at the top). I know it's a little hidden.

If you find values that seem better, let us know so we can test them out!

**Comment by designfrontier** [comment]
Will do!

**Comment by designfrontier** [comment]
I am going to close this. The main thing I've noticed is some real heat sensitivity with the shield. The longer runs in my un cooled garage produced gradually more chatter in the cut. Initial cuts were fantastic with 0.83.
