### ISSUE TITLE
Errors shown while compiling and uploading arduino code to arduino board

### ISSUE THREAD

**Issue by wjcarman** [MaslowCNC/Firmware#290]
I followed the instructions to download Arduino IDE and download latest firmware (version 0.86 as I write this).  I opened the file "cnc_ctrl_v1.ino" and when I hit upload it appears to upload to the mega board but there are a long list of errors in orange that show up while it's compiling and getting ready to send it to the board.

I'm not deeply experienced with Arduino but is this normal every time you upload a file? It still says "done uploading" so I assume it's uploaded properly but I am not sure.

I have taken a screenshot which shows the Arduino IDE screen right after I finished uploading with all of the errors showing in orange.

Thanks,
Wade

![maslow cnc arduino upload errors](https://user-images.githubusercontent.com/18267149/29745592-f9c266dc-8a73-11e7-9d27-b878d7a9696b.jpg)

**Comment by designfrontier** [comment]
I believe those are just compiler warnings. They pop up every time I've compiled a version and have never caused an issue. Errors will prevent the compiler from completing and the upload will not happen.
