### ISSUE TITLE
Spindle Control

### ISSUE THREAD

**Issue by albinger** [MaslowCNC/Firmware#3]
The basic spindle code seems to be in place.  The way it is written the spindle pin is directly set inside the code to handle "S" instructions.

```
if(readString[0] == 'S' || readString[0] == 's'){
    if(readString[1] == '5'){
        digitalWrite(spindle, HIGH);       
    }
    if(readString[1] == '0'){
        digitalWrite(spindle, LOW);
    }
    Serial.println("gready");
    readString = "";
}
```

I'd prefer to set a spindle() function that gets called to set the pin and store desired state.  This way ESTOP code could stop the spindle and then upon clearing could spin up the spindle again before letting the normal processing continue.  

I can implement this if you like.  Just give me a nod if you agree.

-Andrew

**Comment by BarbourSmith** [comment]
Because the firmware is now controlling a 3HP motor, I would like to keep the control of when the motor is on and off manual for now. If it's ok I'd like to close this issue.

**Comment by davidelang** [comment]
Please just mark it as a future item instead of closing it. Even if we are 
controlling a large motor, some people are going to want this.

David Lang

**Comment by BarbourSmith** [comment]
I added some labels. I don't really have the ability to leave the issue open without it cluttering up the issues queue, but I agree with you that it's something people will want. 

My concern is that for liability reasons, I don't want to have that as an option. 

What about this as a compromise. I will put the code in to turn on and off the spindle, but I will leave it commented out. That way if people want to they can go in and un-comment the relevant lines, but it won't be a part of the main code.

Is that an acceptable workaround?

**Comment by davidelang** [comment]
On Sun, 4 Dec 2016, BarbourSmith wrote:

> I added some labels. I don't really have the ability to leave the issue open without it cluttering up the issues queue, but I agree with you that it's something people will want.

I think you can make the default issue view exclude issues with a given tag (if 
you can't make it the default, you can make a view like that for your use and 
bookmark it)

> My concern is that for liability reasons, I don't want to have that as an option.
>
> What about this as a compromise. I will put the code in to turn on and off the spindle, but I will leave it commented out. That way if people want to they can go in and un-comment the relevant lines, but it won't be a part of the main code.

code that is never tested will be buggy

> Is that an acceptable workaround?

I'd leave the code in, but have the controller not have anything wired to the 
pin (other than possibly a LED). This would require someone not just 
uncommenting code, but physically changing the wiring to make it work.

I'm not sure I get the liability issue, there are so many ways that things could 
be used in a way that could hurt someone that I don't see this as being 
significantly different. It's very common for CNC machine code to include 
spindle control, why is your software any different?

If you have a Z axis, you could put something in place to only turn it on if you 
are fully retracted from the workpiece.

David Lang

**Comment by BarbourSmith** [comment]
This is now fully supported 😃
