### ISSUE TITLE
Replace Hard coded Encodersteps Constant

### ISSUE THREAD

**Issue by krkeegan** [MaslowCNC/Firmware#301]
https://github.com/MaslowCNC/Firmware/blob/8ab71d8f757d964160b8d99a47b0218c38250766/cnc_ctrl_v1/MotorGearboxEncoder.cpp#L165

This constant 7364.0 in this line would cause errors for anyone using a non-maslow encoder.  It also isn't quite right as the value is actually 7363.77025037.

The constant should be calculated using the encoderSteps setting likely by querying its parent axis.

**Comment by BarbourSmith** [comment]
Should be fixed in #306 

Great catch @krkeegan !

**Comment by krkeegan** [comment]
Awesome, looks good to me.

**Comment by designfrontier** [comment]
Do we want to convert to `7363.77025037` instead of `7364.0`? Not sure what the implications of that would be. Could go to a shorter form like `7363.8`

**Comment by krkeegan** [comment]
@BarbourSmith 's solution is to calculate the constant using the encoder resolution:

https://github.com/MaslowCNC/Firmware/blob/4a9085ba8d4a7c09ad65af6161d3e977ddf28380/cnc_ctrl_v1/MotorGearboxEncoder.cpp#L161

I don't know how precision works in C but I assume that gets us the full precision.
