### ISSUE TITLE
Save Integral Term to EEPROM

### ISSUE THREAD

**Issue by krkeegan** [MaslowCNC/Firmware#303]
When the Arduino starts up the integral term is zero.  As a result the first few moves are less than accurate until enough "history" had built up in the term to be of use.  It may not be a big deal, but it would be worthwhile to save the term to EEPROM to avoid this.

**Comment by BarbourSmith** [comment]
Great suggestion! I know exactly what you are talking about, but I hadn't thought of a solution

**Comment by krkeegan** [comment]
At the moment, this isn't an issue because the newer suggested PID tunings don't use Ki values at all.

**Comment by BarbourSmith** [comment]
I would feel good about closing this one after merging 😀

**Comment by krkeegan** [comment]
Closing, as I don't think using Ki will ever be a good idea without some substantial work.
