### ISSUE TITLE
Pointer warning

### ISSUE THREAD

**Issue by davekopecek** [MaslowCNC/Firmware#349]
I'm getting the following warning when I upload 0.99 to the Maslow
 
````
sketch\number.c: In function 'bc_str2num':
sketch\number.c:1523:7: warning: assignment discards 'const' qualifier from pointer target type
   ptr = str;
       ^
````

**Comment by blurfl** [comment]
The warning is a nuisance, but it can be ignored. Here's a previousl [discussion.](https://forums.maslowcnc.com/t/errors-shown-while-compiling-and-uploading-arduino-code-to-arduino-boa/556])

**Comment by BarbourSmith** [comment]
Good to close?

**Comment by krkeegan** [comment]
Yeah, I think I have tried to squelch this error before.  Are we even using the number library anymore?  It was also part of bcconfig.h?  Anyone remember why these were included, I don't think we use them anymore and dropping them from the repo would get rid of this warning.

**Comment by BarbourSmith** [comment]
No, you are totally right I think we can safely remove them. They were used at one point in the kinematics to address rounding errors, but that issue was fixed quite a while ago I believe
