### ISSUE TITLE
An error occurred while uploading the sketch

### ISSUE THREAD

**Issue by BBHW** [MaslowCNC/Firmware#416]
Trying to upload the latest firmware and I am getting this error.  I tried it several times with the same result.

Arduino: 1.8.5 (Windows Store 1.8.10.0) (Windows 10), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

Sketch uses 53700 bytes (21%) of program storage space. Maximum is 253952 bytes.
Global variables use 1867 bytes (22%) of dynamic memory, leaving 6325 bytes for local variables. Maximum is 8192 bytes.
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_getsync(): timeout communicating with programmer
An error occurred while uploading the sketch

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by BBHW** [comment]
Here is a more detailed error after setting verbose output during compilation.

Arduino: 1.8.5 (Windows Store 1.8.10.0) (Windows 10), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\tools-builder -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr -built-in-libraries C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries -libraries C:\Users\searsa\Documents\Arduino\libraries -fqbn=arduino:avr:mega:cpu=atmega2560 -ide-version=10805 -build-path C:\Users\searsa\AppData\Local\Temp\arduino_build_900390 -warnings=none -build-cache C:\Users\searsa\AppData\Local\Temp\arduino_cache_664973 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr -prefs=runtime.tools.avr-gcc.path=C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr -verbose C:\Users\searsa\Downloads\Firmware-1.09\Firmware-1.09\cnc_ctrl_v1\cnc_ctrl_v1.ino
C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\arduino-builder -compile -logger=machine -hardware C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\tools-builder -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr -built-in-libraries C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries -libraries C:\Users\searsa\Documents\Arduino\libraries -fqbn=arduino:avr:mega:cpu=atmega2560 -ide-version=10805 -build-path C:\Users\searsa\AppData\Local\Temp\arduino_build_900390 -warnings=none -build-cache C:\Users\searsa\AppData\Local\Temp\arduino_cache_664973 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr -prefs=runtime.tools.avr-gcc.path=C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr -verbose C:\Users\searsa\Downloads\Firmware-1.09\Firmware-1.09\cnc_ctrl_v1\cnc_ctrl_v1.ino
Using board 'mega' from platform in folder: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr
Using core 'arduino' from platform in folder: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr
Detecting libraries used...
"C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   "-IC:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\variants\mega" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\cnc_ctrl_v1.ino.cpp" -o "nul"
"C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   "-IC:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\variants\mega" "-IC:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\libraries\EEPROM\src" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\cnc_ctrl_v1.ino.cpp" -o "nul"
"C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   "-IC:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\variants\mega" "-IC:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\libraries\EEPROM\src" "-IC:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Servo\src" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\cnc_ctrl_v1.ino.cpp" -o "nul"
Using cached library dependencies for file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Axis.cpp
Using cached library dependencies for file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Encoder.cpp
Using cached library dependencies for file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\GCode.cpp
Using cached library dependencies for file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Kinematics.cpp
Using cached library dependencies for file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Motion.cpp
Using cached library dependencies for file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Motor.cpp
Using cached library dependencies for file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\MotorGearboxEncoder.cpp
Using cached library dependencies for file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\NutsAndBolts.cpp
Using cached library dependencies for file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\PID_v1.cpp
Using cached library dependencies for file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Probe.cpp
Using cached library dependencies for file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Report.cpp
Using cached library dependencies for file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\RingBuffer.cpp
Using cached library dependencies for file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Settings.cpp
Using cached library dependencies for file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\SimavrSerial.cpp
Using cached library dependencies for file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Spindle.cpp
Using cached library dependencies for file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\System.cpp
Using cached library dependencies for file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Testing.cpp
Using cached library dependencies for file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\TimerOne.cpp
Using cached library dependencies for file: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Servo\src\avr\Servo.cpp
Using cached library dependencies for file: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Servo\src\nrf52\Servo.cpp
Using cached library dependencies for file: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Servo\src\sam\Servo.cpp
Using cached library dependencies for file: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Servo\src\samd\Servo.cpp
Using cached library dependencies for file: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Servo\src\stm32f4\Servo.cpp
Generating function prototypes...
"C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   "-IC:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\variants\mega" "-IC:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\libraries\EEPROM\src" "-IC:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Servo\src" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\cnc_ctrl_v1.ino.cpp" -o "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\preproc\ctags_target_for_gcc_minus_e.cpp"
"C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\tools-builder\ctags\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\preproc\ctags_target_for_gcc_minus_e.cpp"
Compiling sketch...
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Axis.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Encoder.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\GCode.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Kinematics.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Motion.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Motor.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\MotorGearboxEncoder.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\NutsAndBolts.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\PID_v1.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Probe.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Report.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\RingBuffer.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Settings.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\SimavrSerial.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Spindle.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\System.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Testing.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\TimerOne.cpp.o
"C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR   "-IC:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\cores\arduino" "-IC:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\variants\mega" "-IC:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\libraries\EEPROM\src" "-IC:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Servo\src" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\cnc_ctrl_v1.ino.cpp" -o "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\cnc_ctrl_v1.ino.cpp.o"
Compiling libraries...
Compiling library "EEPROM"
Compiling library "Servo"
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\libraries\Servo\avr\Servo.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\libraries\Servo\nrf52\Servo.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\libraries\Servo\sam\Servo.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\libraries\Servo\samd\Servo.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\libraries\Servo\stm32f4\Servo.cpp.o
Compiling core...
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\wiring_pulse.S.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\WInterrupts.c.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\hooks.c.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\wiring.c.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\wiring_analog.c.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\wiring_digital.c.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\wiring_pulse.c.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\wiring_shift.c.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\CDC.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\HardwareSerial.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\HardwareSerial0.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\HardwareSerial1.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\HardwareSerial2.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\HardwareSerial3.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\IPAddress.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\PluggableUSB.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\Print.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\Stream.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\Tone.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\USBCore.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\WMath.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\WString.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\abi.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\main.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\new.cpp.o
Using previously compiled file: C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\core\core.a
Archiving built core (caching) in: C:\Users\searsa\AppData\Local\Temp\arduino_cache_664973\core\core_arduino_avr_mega_cpu_atmega2560_a94ab6aaf61dfb93b4a8079c694a14c2.a
Linking everything together...
"C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr/bin/avr-gcc" -w -Os -g -flto -fuse-linker-plugin -Wl,--gc-sections,--relax -mmcu=atmega2560  -o "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390/cnc_ctrl_v1.ino.elf" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Axis.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Encoder.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\GCode.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Kinematics.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Motion.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Motor.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\MotorGearboxEncoder.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\NutsAndBolts.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\PID_v1.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Probe.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Report.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\RingBuffer.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Settings.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\SimavrSerial.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Spindle.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\System.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\Testing.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\TimerOne.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\sketch\cnc_ctrl_v1.ino.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\libraries\Servo\avr\Servo.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\libraries\Servo\nrf52\Servo.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\libraries\Servo\sam\Servo.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\libraries\Servo\samd\Servo.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390\libraries\Servo\stm32f4\Servo.cpp.o" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390/core\core.a" "-LC:\Users\searsa\AppData\Local\Temp\arduino_build_900390" -lm
"C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr/bin/avr-objcopy" -O ihex -j .eeprom --set-section-flags=.eeprom=alloc,load --no-change-warnings --change-section-lma .eeprom=0  "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390/cnc_ctrl_v1.ino.elf" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390/cnc_ctrl_v1.ino.eep"
"C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr/bin/avr-objcopy" -O ihex -R .eeprom  "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390/cnc_ctrl_v1.ino.elf" "C:\Users\searsa\AppData\Local\Temp\arduino_build_900390/cnc_ctrl_v1.ino.hex"
Using library EEPROM at version 2.0 in folder: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\libraries\EEPROM 
Using library Servo at version 1.1.2 in folder: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries\Servo 
Sketch uses 53700 bytes (21%) of program storage space. Maximum is 253952 bytes.
Global variables use 1867 bytes (22%) of dynamic memory, leaving 6325 bytes for local variables. Maximum is 8192 bytes.
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_getsync(): timeout communicating with programmer
An error occurred while uploading the sketch

**Comment by blurfl** [comment]
Based on this line:
>avrdude: stk500v2_getsync(): timeout communicating with programmer

it looks to me like communication to the Arduino hasn't been successful.
 Usually the answer to this is in the Arduino IDE, check in the Tools menu - the Port should have COMx (Arduino Mega or Mega 2560) selected.

**Comment by BBHW** [comment]
That was it!
