### ISSUE TITLE
Add support for configuring spindle control signal high/low.

### ISSUE THREAD

**Issue by CptanPanic** [MaslowCNC/Firmware#436]
Currently I am setting up my spindle control logic to connect to a super-pid spindle controller.  It uses an active low to trigger it, and I notice in code that there is almost support to have option to have active low or high but it is hardcoded to be `boolean activeHigh = true;`   Enhancement would be to add ability to pull this value from sysSettings  , and a '$' command to set it.

Thanks.

**Comment by CptanPanic** [comment]
I am going to make this and submit a PR.

**Comment by blurfl** [comment]
Instead of adding another setting, how about changing the existing setting for 'Spindle Automation' to a pick list with ['None', ''Relay - Active High', 'Relay - Active Low', 'Servo Operated Switch'] and implementing the logic in Spindle.cpp for all those options. That way non-spindlers won't have to wait for a function they don't have...

**Comment by CptanPanic** [comment]
Yeah that sounds good

**Comment by blurfl** [comment]
Make 'none' the default.
Don't configure the gpio as an output until an M-code that actually turns the spindle on is executed. This will aid to prevent turning on the spindle on Arduino reset. Any other precautions to prevent inadvertent activation would be a very good idea. Make it safe.

**Comment by blurfl** [comment]
```
what happens when the arduno looses power or reboots, if that's
going to cause the router to start spinning
```
Unfortunately, I don't think we can't know that. There are many ways to use a gpio pin to cause a change in an external circuit. Few people consider failure modes when lashing up a control like this.

**Comment by CptanPanic** [comment]
Since pin isn't written to until M3 is sent, it seems that the internal resistor is activated by default on boot so the active low isn't triggered, at least for my device.
