### ISSUE TITLE
ROBOT.md and Robot.md conflict on Windows systems

### ISSUE THREAD

**Issue by BenjaminPelletier** [MaslowCNC/Firmware#452]
Windows file names are case-insensitive when matching, so the presence of both ROBOT.md and Robot.md in the repo causes problems when trying to interact with the repo on Windows.  One of these files should be deleted from the repo.

**Comment by BarbourSmith** [comment]
Thanks for the heads up. Robot.md has been deleted

**Comment by blurfl** [comment]
No wonder it disappeared while I was looking! 👍😁
