### ISSUE TITLE
Firmware upload

### ISSUE THREAD

**Issue by willeyaz** [MaslowCNC/Firmware#475]
I unable to upload the 1.24 firmware. I get this message
![image](https://user-images.githubusercontent.com/34918938/47969438-dcac4a00-e034-11e8-9f20-c4b60e7cac7d.png)

**Comment by blurfl** [comment]
When you unzip the firmware, don’t move any of the files. Just open the .ino file and the rest of the pieces will be in the proper place.

**Comment by blurfl** [comment]
This appears to have been solved.
