### ISSUE TITLE
error timeout when downloading audrino

### ISSUE THREAD

**Issue by oscar5208** [MaslowCNC/Firmware#487]
while downloading aurino to laptop got below error?can i download all software to my main pc then put sketch on thumb drive for laptop to use on cnc machine or does all 
![audrno up;lod error](https://user-images.githubusercontent.com/48333470/54500352-552feb00-48f2-11e9-8815-8a375baa11a5.PNG)
software have to be on laptop attached to machine?
![audrno up;lod error](https://user-images.githubusercontent.com/48333470/54500363-8b6d6a80-48f2-11e9-81c4-29c25921b5af.PNG)

**Comment by GeroBH** [comment]
Responded to the post in the Forum, as this does not seem to be an Firmware issue.
https://forums.maslowcnc.com/t/laptop-set-up-with-audrino-software-download/9186

If you feel OK to continue the troubleshooting in the Forum, please close this issue here on Git.
Regards, Gero

**Comment by blurfl** [comment]
Can we close this?

**Comment by BarbourSmith** [comment]
Yeah I think it is safe to close this
