### ISSUE TITLE
New Feature: Z Axis limits to prevent equipment strain

### ISSUE THREAD

**Issue by ariasr** [MaslowCNC/Firmware#542]
I have made some small tweaks to the code to be able to set upper and lower limits for the z axis in order to prevent equipment strain.

I have added two variables to settings 
     float zAxisUpperLimit
     float zAxisLowerLimit

I have created 4 "B" commands
     B17 Set the z axis upper limit to the current z axis position
     B18 Set the z axis lower limit to the current z axis position
     B19 Clear z axis limits
     B20 Echo z axis limits

I have made some changes to Axis, GCode and Settings classes.

I would like to contribute it to the project.

Best Regards

**Comment by davidelang** [comment]
once you get the robot e-mail, vote by adding a thumbs up to the robot's post, 
that will merge your pull request unless people vote thumbs down.

David Lang

**Comment by ariasr** [comment]
I have not been able to do a pull request. Perhaps I don't have the right permisions?

**Comment by davidelang** [comment]
you should be able to fork the repo and create a pull request from your fork.

David Lang

**Comment by ariasr** [comment]
Thank you. I finally figured it out and generated the pull request. Its already there for aproval.

**Comment by davidelang** [comment]
be sure to give yoursef a thumbs up (on the robot's post)

David Lang
