### ISSUE TITLE
firmware error

### ISSUE THREAD

**Issue by cstanl3y** [MaslowCNC/Firmware#547]
After loading firmware selecting the board and com port and clicking upload tab I get the following error:
Arduino: 1.8.12 (Windows 10), Board: “Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)”

cnc_ctrl_v1:36:10: fatal error: Maslow.h: No such file or directory

#include “Maslow.h”

      ^~~~~~~~~~
compilation terminated.

exit status 1
Maslow.h: No such file or directory

This report would have more information with
“Show verbose output during compilation”
option enabled in File -> Preferences.

I went back and reloaded everthing again same error.

**Comment by GeroBH** [comment]
Hi, this error shows up if the Firmware is not "un-ziped" / extracted before uploading to the Arduino. You should be able to solve it by extracting the compressed file to a folder of your choice and upload it from there.
![screenshot](https://user-images.githubusercontent.com/25812652/84467066-9cd32d00-ac83-11ea-85af-062f48c80c1c.jpg)

**Comment by cstanl3y** [comment]
Thank you. It’s been a learning curve for sure.

Sent from my iPad

On Jun 11, 2020, at 10:07 PM, Gero <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, this error shows up if the Firmware is not "un-ziped" / extracted before uploading to the Arduino. You should be able to solve it by extracting the compressed file to a folder of your choice and upload it from there.
[screenshot]<https://user-images.githubusercontent.com/25812652/84467066-9cd32d00-ac83-11ea-85af-062f48c80c1c.jpg>

**Comment by BarbourSmith** [comment]
Thanks @GeroBH ❤️ ❤️
