### ISSUE TITLE
Interpolating chain lengths long distances could lead to curved movements

### ISSUE THREAD

**Issue by brandonagr** [MaslowCNC/Firmware#56]
I just briefly browsed the firmware, looking at CNC_Functions.h move function, it appears that you are getting the chain lengths at start of move and at destination and then linearly interpolating the chain lengths over time. 

If you have a long move, could this result in a curved movement? Was wondering if you have tested to see if this is not an issue. (Maybe what is generating your gcode doesn't produce long movements?)

![image](https://cloud.githubusercontent.com/assets/338022/19397885/61ba7b2a-920f-11e6-89c4-da7ae39578ec.png)

**Comment by dinglewanker** [comment]
Yes.  I was wondering this same thing.

**Comment by BarbourSmith** [comment]
I'm sorry guys for not seeing this sooner. I'm so used to being the only one in here that I didn't check to see if anyone else had tagged a bug. Thank you for noting that. It was absolutely a bug (or really more of an incomplete feature, there's still a good amount of those).

At some point I fixed the issue I believe by calling the kinematics function at each step along the line. The new version looks like this:

    
    while(abs(numberOfStepsTaken) < abs(finalNumberOfSteps)){
        
        float whereXShouldBeAtThisStep = xStartingLocation + (numberOfStepsTaken*xStepSize);
        float whereYShouldBeAtThisStep = yStartingLocation + (numberOfStepsTaken*yStepSize);
        
        kinematics.inverse(whereXShouldBeAtThisStep,whereYShouldBeAtThisStep,&aChainLength,&bChainLength);
        
        
        leftAxis.write(aChainLength);
        rightAxis.write(bChainLength);
        numberOfStepsTaken++;
        
        returnPoz();
        
        delay(timePerStep);
    }

Does that look like it solves the issue to you?

**Comment by BarbourSmith** [comment]
I'm going to close this issue if nobody objects. Thanks again for pointing it out.
